### PR TITLE
Add osx-arm64

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
This is ready to go @conda-forge/geographiclib-cpp @cffk

**Comment by cffk** [comment]
I'll take a look at this today.

**Review by cffk — APPROVED** [review]
This look fine.  Thanks.  (I should note that as a conda-forge novice I didn't wade into the various changes outside the recipe directory.)

**Comment by Tobias-Fischer** [comment]
Thanks @cffk - you are the only maintainer of this repo, so it would be great if you could merge :)

**Comment by Tobias-Fischer** [comment]
Happy to add myself as maintainer if you want.

**Pull request merged**
