### PR TITLE
Add missing run_export

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Issue was discovered in https://github.com/RoboStack/ros-noetic/issues/117 and will be fixed by this PR.

**Comment by cffk** [comment]
This looks fine.  I don't count myself as a conda expert.  However, on the issue of the dependency requirement for downstream packages, yes, obviously they will inherit the dependency on geographiclib.

**Comment by Tobias-Fischer** [comment]
Thanks for checking @cffk!

@wolfv @traversaro: could you please also have a look and approve/merge the PR?

Thanks, Tobi

**Comment by wolfv** [comment]
Pinning looks fine (https://abi-laboratory.pro/index.php?view=timeline&l=geographiclib).

This is ready to go in my opinion

**Review by traversaro — APPROVED** [review]

**Pull request merged**
