### PR TITLE
enable aarch64/ppc64

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Hi @cffk, do you have any objections in just disabling the one failing test for aarch/ppc?

If so, this is ready to be merged.

**Comment by cffk** [comment]
> Hi @cffk, do you have any objections in just disabling the one failing test for aarch/ppc?
> 
If possible, it would be nice to figure out why this test is failing.  Can you give me that output for
```bash
GeodSolve -i --input-string "20.001 0 20.001 0" -f
```

**Comment by Tobias-Fischer** [comment]
Sure: 
- aarch: `20.00100000 0.00000000 180.00000000 20.00100000 0.00000000 180.00000000 0.000 0.00000000 -0.000 1.0000000000 1.0000000000 0`
- amd64: `20.00100000 0.00000000 180.00000000 20.00100000 0.00000000 180.00000000 0.000 0.00000000 0.000 1.0000000000 1.0000000000 0`

So it seems to be the `-0.000` which is the issue.

**Comment by Tobias-Fischer** [comment]
Cool - all fixed :). I think this is ready @cffk

**Comment by cffk** [comment]
> Cool - all fixed :). I think this is ready @cffk

Thanks.  Yes this looks good.  I'll migrate the optional minus sign for the output of this test into the source.

In looking at the code, I see that I explicitly add `0.0` to `m12` to convert `-0.0` to `+0.0`.  The fact that this quantity is still displaying as `-0.000` means (I think) that it is really less than `0`.  Perhaps you can give me the results of adding `-p 12` to the command line so I can check.

**Review by cffk — APPROVED** [review]

**Comment by Tobias-Fischer** [comment]
Indeed that seems to be the case: `20.001000000000001 0.000000000000000 180.000000000000000 20.001000000000001 0.000000000000000 180.000000000000000 0.0000000002 0.000000000000001 -0.0000000001 0.99999999999999989 0.99999999999999989 0.000`

**Comment by Tobias-Fischer** [comment]
Hi @cffk, should we merge this for now, and then deal with a proper fix upstream later on?

**Comment by cffk** [comment]
> Hi @cffk, should we merge this for now, and then deal with a proper fix upstream later on?

I just merged.

**Comment by cffk** [comment]
@Tobias-Fischer Hi, I just checked in a fix for the problem exhibited by test `GeodSolve82`.  GeodSolve shouldn't be returning negative `s12` or `m12` for short geodesics; this fix (on GeographicLib's `devel` branch) takes steps to make this true.  This would obviate the need to permit a negative sign in the results from `GeodSolve82`.
If you have the energy perhaps you can check that the fix works for `aarch`.  If not, we can catch up on this issue with the next release.

**Comment by Tobias-Fischer** [comment]
Hi, I suggest to wait till the next release - it's not super high priority I guess.

**Pull request merged**
